version: "3.8"
services:
  db:
    container_name: pets-database
    ports:
      - 3306:3306
    build: ./db
    env_file:
      - ./db/db.env
    restart: always
  web:
    container_name: pets-api
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
