version: "3.8"
services:
  db:
    build: ./db
    env_file:
    - db.env
    restart: always
  web:
    build: ./web
    env_file:
    - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure